[package]
name = "rusty-halloween"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio = "0.4.1"
interprocess = "1.1.1"
packed_struct = "0.10.0"
protobuf = "3.2.0"
