[build]
target = "xtensa-esp32s2-espidf"

[target.xtensa-esp32s2-espidf]
linker = "ldproxy"
runner = "web-flash --chip esp32s2"
rustflags = [ "--cfg",  "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32s2"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.3.2"
