on:
  push:

name: ARMv7 build

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: armv7-unknown-linux-gnueabihf
          override: true

      # Install cargo-chef
      - name: Install cargo-chef
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-chef

      # Generate recipe.json
      - name: Generate recipe
        run: cargo chef prepare --recipe-path recipe.json

      # Cache dependencies based on recipe.json
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin/cross  # Cache cross binary
          key: ${{ runner.os }}-cargo-${{ hashFiles('recipe.json') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      # Build dependencies only
      - name: Build dependencies
        run: cargo chef cook --target armv7-unknown-linux-gnueabihf --release --features pi

      # Build actual project
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release --features pi

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: pi-binary
          path: target/armv7-unknown-linux-gnueabihf/release/rusty-halloween
