on:
  push:

name: ARMv7 build

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Cache dependencies
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            ~/.cargo/bin/cross
          key: ${{ runner.os }}-cross-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cross-

      # Install cross only if not cached
      - name: Install cross
        run: |
          if ! command -v cross &> /dev/null; then
            cargo install cross
          fi

      # Build with cross
      - name: Build
        run: cross build --target armv7-unknown-linux-gnueabihf --release --features pi

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: pi-binary
          path: target/armv7-unknown-linux-gnueabihf/release/rusty-halloween
