on: [push]

name: Check

jobs:
  fmt:
    name: Rust project - fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  test-x86:
    name: Rust project - test x86
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Install ALSA
        run: sudo apt-get install -y libasound2-dev

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  test-arm:
    name: Rust project - test arm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: armv7-unknown-linux-gnueabihf
          override: true

      - name: Install ALSA
        run: sudo apt-get install -y libasound2-dev

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target armv7-unknown-linux-gnueabihf --release --features pi

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

  clippy-x86:
    name: Rust project - clippy x86
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy

      - name: Install ALSA
        run: sudo apt-get install -y libasound2-dev

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

  clippy-arm:
    name: Rust project - clippy arm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: armv7-unknown-linux-gnueabihf
          override: true
          components: clippy

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: clippy
          args: --target armv7-unknown-linux-gnueabihf --release --features pi
