# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"R\n\x0bpicoMessage\x12\x1f\n\tprojector\x18\x01 \x01(\x0b\x32\n.ProjectorH\x00\x12\x17\n\x05light\x18\x02 \x01(\x0b\x32\x06.LightH\x00\x42\t\n\x07payload\"P\n\tProjector\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12*\n\x10\x64rawInstructions\x18\x02 \x03(\x0b\x32\x10.DrawInstruction\"\xf0\x02\n\x06Header\x12\x18\n\x0bprojectorId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x17\n\npointCount\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x11\n\x04home\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12\x13\n\x06\x65nable\x18\x04 \x01(\x08H\x03\x88\x01\x01\x12\x1f\n\x12\x63onfiguration_mode\x18\x05 \x01(\x08H\x04\x88\x01\x01\x12\x1a\n\rdraw_boundary\x18\x06 \x01(\x08H\x05\x88\x01\x01\x12\x14\n\x07oneshot\x18\x07 \x01(\x08H\x06\x88\x01\x01\x12\x1a\n\rspeed_profile\x18\x08 \x01(\x05H\x07\x88\x01\x01\x12\x15\n\x08\x63hecksum\x18\t \x01(\x08H\x08\x88\x01\x01\x42\x0e\n\x0c_projectorIdB\r\n\x0b_pointCountB\x07\n\x05_homeB\t\n\x07_enableB\x15\n\x13_configuration_modeB\x10\n\x0e_draw_boundaryB\n\n\x08_oneshotB\x10\n\x0e_speed_profileB\x0b\n\t_checksum\"\xc9\x01\n\x0f\x44rawInstruction\x12\x13\n\x06xCoOrd\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x06yCoOrd\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x10\n\x03red\x18\x03 \x01(\x05H\x02\x88\x01\x01\x12\x12\n\x05green\x18\x04 \x01(\x05H\x03\x88\x01\x01\x12\x11\n\x04\x62lue\x18\x05 \x01(\x05H\x04\x88\x01\x01\x12\x15\n\x08\x63hecksum\x18\x06 \x01(\x08H\x05\x88\x01\x01\x42\t\n\x07_xCoOrdB\t\n\x07_yCoOrdB\x06\n\x04_redB\x08\n\x06_greenB\x07\n\x05_blueB\x0b\n\t_checksum\"I\n\x05Light\x12\x14\n\x07lightId\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x06\x65nable\x18\x02 \x01(\x08H\x01\x88\x01\x01\x42\n\n\x08_lightIdB\t\n\x07_enableb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PICOMESSAGE._serialized_start=16
  _PICOMESSAGE._serialized_end=98
  _PROJECTOR._serialized_start=100
  _PROJECTOR._serialized_end=180
  _HEADER._serialized_start=183
  _HEADER._serialized_end=551
  _DRAWINSTRUCTION._serialized_start=554
  _DRAWINSTRUCTION._serialized_end=755
  _LIGHT._serialized_start=757
  _LIGHT._serialized_end=830
# @@protoc_insertion_point(module_scope)
