# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schema.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cschema.proto\"k\n\x0bpicoMessage\x12\x1f\n\tprojector\x18\x01 \x01(\x0b\x32\n.ProjectorH\x00\x12\x17\n\x05light\x18\x02 \x01(\x0b\x32\x06.LightH\x00\x12\x17\n\x05\x61udio\x18\x03 \x01(\x0b\x32\x06.AudioH\x00\x42\t\n\x07payload\"Q\n\tProjector\x12\x17\n\x06header\x18\x01 \x01(\x0b\x32\x07.Header\x12+\n\x11\x64raw_instructions\x18\x02 \x03(\x0b\x32\x10.DrawInstruction\"\xbe\x01\n\x06Header\x12\x14\n\x0cprojector_id\x18\x01 \x01(\x05\x12\x13\n\x0bpoint_count\x18\x02 \x01(\x05\x12\x0c\n\x04home\x18\x03 \x01(\x08\x12\x0e\n\x06\x65nable\x18\x04 \x01(\x08\x12\x1a\n\x12\x63onfiguration_mode\x18\x05 \x01(\x08\x12\x15\n\rdraw_boundary\x18\x06 \x01(\x08\x12\x0f\n\x07oneshot\x18\x07 \x01(\x08\x12\x15\n\rspeed_profile\x18\x08 \x01(\x05\x12\x10\n\x08\x63hecksum\x18\t \x01(\x08\"m\n\x0f\x44rawInstruction\x12\x0e\n\x06xCoOrd\x18\x01 \x01(\x05\x12\x0e\n\x06yCoOrd\x18\x02 \x01(\x05\x12\x0b\n\x03red\x18\x03 \x01(\x05\x12\r\n\x05green\x18\x04 \x01(\x05\x12\x0c\n\x04\x62lue\x18\x05 \x01(\x05\x12\x10\n\x08\x63hecksum\x18\x06 \x01(\x08\")\n\x05Light\x12\x10\n\x08light_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x65nable\x18\x02 \x01(\x08\"\x1b\n\x05\x41udio\x12\x12\n\naudio_file\x18\x01 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schema_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PICOMESSAGE._serialized_start=16
  _PICOMESSAGE._serialized_end=123
  _PROJECTOR._serialized_start=125
  _PROJECTOR._serialized_end=206
  _HEADER._serialized_start=209
  _HEADER._serialized_end=399
  _DRAWINSTRUCTION._serialized_start=401
  _DRAWINSTRUCTION._serialized_end=510
  _LIGHT._serialized_start=512
  _LIGHT._serialized_end=553
  _AUDIO._serialized_start=555
  _AUDIO._serialized_end=582
# @@protoc_insertion_point(module_scope)
